n1 = int(input("primeiro número: "))
n2 = int(input("segundo número: "))
print(f'A soma vale { n1 + n2}')
print(f'A subtração vale {n1 - n2 }')
print(f'A multiplicação vale {n1 * n2}')
print(f'A divisão vale {n1 / n2:.3f}')
print(f'A potenciação vale {n1**n2}')
print(f'O resto da divisão vale {n1 % n2}')
print(f'A divisão inteira vale {n1 // n2 }')